Repository lemonade-sdk/lemonade, pull requests merged in 2025-08, with the labels that each got.

#279 Update installation commands in dev-cli Readme
  docs/dev_cli/README.md
Labels: documentation

#315 Fix perf report bug on single iteration for bench tool
  src/lemonade/tools/report/table.py
Labels: bug

#317 Fix Lemonade Server URL reference
  src/lemonade_install/install.py
Labels: codex
